### ISSUE TITLE
Edit configuration of existing widgets

### ISSUE THREAD

**Issue by billmania** [billmania/roboquest_ui#107]
After a widget has been configured and added to the UI, it can be removed from the UI, but there's no way to adjust its configuration.
Implement a mechanism for adjusting an existing widget's configuration. Coordinate the design, from a UX perspective, with the mechanism for removing a widget and for re-positioning a widget.

**Comment by MarkSkinner92** [comment]
**Step 1**
Move all the logic for configuring widgets into one file

**Step 2**
Create a way for users to open the menu on a particular widget

- Create a kebab menu that appears in the top right of a widget, only when the mouse is hovering over the widget
- Add click functionality to the kebab, opening up to a drop down menu to edit
- Make menu disappear when option is clicked.

**Step 3**
Display a custom configuration panel for the particular widget being edited

- Load in the current configuration of the widget being edited
- save the data of the UI panel into the widget being edited
