### ISSUE TITLE
Slider widget doesn't repeat the current slider value

### ISSUE THREAD

**Issue by billmania** [billmania/roboquest_ui#31]
Moving the slider doesn't cause the current slider value to be published until the mouseUp event. The current slider value is emitted once and then the interval resumes emitting what looks like the default slider value, even though the slider button is not at that value.

To reproduce, start the backend, start the frontend, connect the browser, use **ros2 topic echo /servos** to display the angle values. Move the slider without a mouseUP and note the published value doesn't change. Cause the mouseUp event and note a single published message at the current value after which the default value is continually published.

**Comment by billmania** [comment]
The payload emitted onto the socket is malformed AND it is not being sent periodically.The malformed payload is
```
["angle,name":"178"]
```

**Comment by SuddenDevelopment** [comment]
duplicate, merged to 26
