### ISSUE TITLE
Add keyboard options for the joystick widget P1

### ISSUE THREAD

**Issue by billmania** [billmania/roboquest_ui#64]
Add the option to add keyboard events to produce the same effect as joystick options. This will allow a student to drive the robot using the keyboard instead of the joystick widget.

- forward 
- reverse
- turn left
- turn right

For each key, the keydown event will start the motion and the keyup event will stop the motion. The speed of motion is fixed by the value in the configuration file.

Add a keyboard driving mode, enabled by button.

This Issue includes the Slider support described originally in Issue #65

**Comment by SuddenDevelopment** [comment]
try to capture the key event to configure. Including key combos?

**Comment by SuddenDevelopment** [comment]
within the joystick widget:

- create a button to switch the joystick widget to a keyboard input "mode"
- create a number of named functions for each distinct event such as "left", "right, "forward", "medium speed", "high speed"
- set each of events from the joystick config to a key
- use jquery keydown event: https://api.jquery.com/keydown/
- speed + direction key would need to be a keypress at the same time to work.
- the resulting values need to set the same joystick events and values, triggering the same emit mechanism the joystick uses. This will mean it keeps the same data scaling etc.

**Comment by billmania** [comment]
1. agreed
2. agreed
3. agreed, including some experimentation to determine which keys can be mapped to events and can bi visually represented on the joystick widget. ie. It will be challenging to select Ctl-PgDn-F11 as the "go faster" key and display it on the widget
4. agreed, with some prototyping to ensure its limits are understood
5. does this mean the separate "speed" key would be a modifier for each separate "direction" key?
6. strong agreement
Thinking more about 5. assume there's exactly one key defined for each of the four directions and a fifth key defined for full-stop. Also, assume there is no "don't release the key and go faster". Then, press the key to start moving and press it again to incrementally increase the speed. Then, press the full-stop key to stop or repeatedly press the opposite direction key to incrementally slow. Keep pressing it to reverse direction.

**Comment by SuddenDevelopment** [comment]
5. yes: direction key will always be low speed. then a speed key would need to be added to increase speed in that direction

**Comment by billmania** [comment]
**Implementation plan**

1. research the jQuery keyboard event capture mechanism
2. add a button to the top of the page which enables and disables "keyboard driving mode"
3. in keyboard mode, capture key events and log them
4. identify/define the functions which are used by joystick motion commands and can be associated with key events
5. map the key events to the joystick motion command functions

**Comment by billmania** [comment]
Change the collection of keys and the way they're handled. Eliminate the STOP key. On keydown, start the motion. On keyup, stop the motion. Implement speed control via a separate slider enabled at all times (ie. it affects the joystick AND the keys).
