### ISSUE TITLE
Throttle emission of slider values

### ISSUE THREAD

**Issue by SuddenDevelopment** [billmania/roboquest_ui#68]
Dragging the slider can cause a high frequency of value emissions, which in turn causes increased latency in the response of the servos. To reduce the latency when dragging the slider, increase the "step" value and don't emit another event unless the value has changed by at least "step" OR a configurable amount of time has elapsed since the last emission.

Do not define an interval for continually emitting the same slider value.

Related to Issue #65

**Comment by billmania** [comment]
After recent changes to the slider implementation, this may no longer be an issue.
