### ISSUE TITLE
Everything selects when using joystick

### ISSUE THREAD

**Issue by MarkSkinner92** [billmania/roboquest_ui#96]
When the user attempts to drags the joystick knob outside the widget (which happens quite frequently) many other text and image elements are highlighted. Planning to fix with a global user-select:none in the CSS

**Comment by billmania** [comment]
@MarkSkinner92 Is this related to Issue #32 or does it overlap that issue?

**Comment by MarkSkinner92** [comment]
It is unrelated to #32. I was using Google Chrome 117.0.5938.132 (Official Build) (64-bit) on my Ubuntu 20.04 laptop

**Comment by MarkSkinner92** [comment]
After some testing, the issue seems to be specific to google Chrome
